[tasks.cli]
workspace = false
command = "cargo"
args = ["run", "-p", "cli", "--", "${@}"]

[tasks.lint]
workspace = false
script = [
    "cargo fmt --check",
    "cargo clippy -- -D warnings",
]

[tasks.check]
workspace = false
command = "cargo"
args = ["check"]

[tasks.check-full]
workspace = false
script = [
    "cargo clean",
    "cargo check",
]

[tasks.fmt]
workspace = false
script = [
    "cargo fmt",
    "cargo clippy --fix --allow-dirty",
]
